public with sharing class CaseTriggerHelper {

    // public static void doSomeBusinessRequirement(List<Account> newAccountList) {
    //     for(Account acct : newAccountList) {
    //         // add Some business Logic
    //     }
    // }

    // public static void updateRelatedContacts(Map<Id, Account> newAccountMap) {
    //     List<Contacts> contacts = [SELECT Id, Phone FROM Contact 
    //          WHERE ID IN :newAccountMap.keySet() ];
    //     for(Contact contact : contacts) {
    //          // do Something 
    //     }
    //     update contacts;
    // }
}
