public class Constants {
    
    public static final String WEB = 'Web';
    public static final String PHONE = 'Phone';
    public static final String EMAIL = 'Email';

    public static final String EXEEDED_ONE_ATTENDEE_PER_WEB_REQUEST = 'EXEEDED ONE ATTENDEE PER WEB REQUEST';
    public static final String ATTACHING_ACCOUNT_FOR_REQUEST_CREATION = 'ATTACHING ACCOUNT FOR REQUEST CREATION';
    public static final String REQUIRE_CONTACTS_FOR_ACCOUNT_CREATION = 'REQUIRE CONTACTS FOR ACCOUNT CREATION';
    public static final String EXCEEDED_THREE_ATTENDEES_PER_PHONE_REQUEST = 'EXCEEDED THREE ATTENDES PER PHONE REQUEST';

    public static final String NEW_STATUS = 'New';
    public static final String WORKING = 'Working';
    public static final String ESCALATED = 'Escalated';
    public static final String CLOSED = 'Closed';

}
